name: Test Workflow
run-name: ${{ github.actor }} lets test docker
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-20.04-arm
    container:
      image: node:20-bookworm-slim
    
    steps:
      - run: echo "Hello Containers"