name: Test Workflow
run-name: ${{ github.actor }} lets test docker
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-22.04
    container:
      image: node:20-bookworm-slim
    
    steps:
      - run: echo "Hello Containers"

  dotnet_test:
    runs-on: ubuntu-24.04-arm
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    
    steps:
      - run: dotnet --version
      - run: cat /proc/cpuinfo
      - run: cat /proc/meminfo